extends SceneTree

const Motion = preload("res://scripts/wr1_motion.gd")
var failures: int = 0
var checks: int = 0

func check(actual: Variant, expected: Variant, label: String) -> void:
	checks += 1
	if actual != expected:
		failures += 1
		push_error("%s: expected %s, got %s" % [label, expected, actual])

func flat_state():
	var state = Motion.new()
	state.width = 80
	state.height = 40
	for row in range(40):
		var cells: Array = []
		cells.resize(80)
		cells.fill(0x73 if row >= 20 else 0xff)
		state.attributes.append(cells)
	state.x = 64
	state.y = 191
	state.gx = 5
	state.gy = 20
	state.phase = 16
	state.facing = 0
	return state

func _initialize() -> void:
	# Acceptance oracle recorded from the running original, not generated by model.
	var trace: Dictionary = JSON.parse_string(FileAccess.get_file_as_string("res://testing/fixtures/wr1_left_walk.json"))
	var state = Motion.new()
	state.configure(JSON.parse_string(FileAccess.get_file_as_string("res://data/wr1/level_01.json")))
	for key in trace.initial:
		if key in ["world_x", "world_y"]:
			continue
		state.set("frame" if key == "sprite" else key, int(trace.initial[key]))
	for expected in trace.updates:
		state.step(false, false, true, false)
		state.scroll_camera()
		var actual: Dictionary = state.snapshot()
		for key in expected:
			check(actual[key], int(expected[key]), "Native walk update %s %s" % [state.ticks, key])

	# Full native jump, including vertical camera following and release on descent.
	trace = JSON.parse_string(FileAccess.get_file_as_string("res://testing/fixtures/wr1_full_jump.json"))
	state = Motion.new()
	state.configure(JSON.parse_string(FileAccess.get_file_as_string("res://data/wr1/level_01.json")))
	check(state.facing, int(trace.initial.facing), "Initial facing confirmed by native jump")
	for key in trace.initial:
		if key not in ["world_x", "world_y"]:
			state.set("frame" if key == "sprite" else key, int(trace.initial[key]))
	for update in trace.updates:
		state.step(update.up, false, false, false)
		state.scroll_camera()
		var actual: Dictionary = state.snapshot()
		for key in update.state:
			check(actual[key], int(update.state[key]), "Native jump replay frame %s %s" % [update.replay_frame, key])

	state = flat_state()
	var heights: Array = []
	for i in range(19):
		state.step(true, false, false, false)
		heights.append(191 - state.y)
	check(heights, [8,16,24,32,40,48,56,64,72,64,56,48,40,32,24,16,8,0,8], "Held jump and repeat")
	state = flat_state()
	for i in range(3):
		state.step(true, false, false, false)
	state.step(false, false, false, false)
	check(state.y, 175, "Release falls immediately")
	state.step(true, false, false, false)
	check([state.y, state.phase], [167, 5], "Repress resumes remaining jump")
	state = flat_state()
	for row in range(state.height):
		state.attributes[row][6] = 0x74
	for i in range(15):
		state.step(true, false, false, false)
	check([191 - state.y, state.phase], [120, 1], "Climb pattern exceeds ordinary jump height")
	state = flat_state()
	state.attributes[15].fill(0x73)
	state.step(true, false, false, false)
	check([state.y, state.phase], [191, 16], "Ceiling stops rise and exhausts phase")
	state = flat_state()
	for row in range(state.height):
		state.attributes[row][4] = 0x73
	state.step(false, false, true, true)
	check(state.x, 72, "Both directions are sequential collision attempts")
	state = flat_state()
	state.attributes[16][8] = 0x73
	state.attributes[17][7] = 0x73
	state.step(false, false, false, true)
	check(state.x, 56, "Right collision rechecks shifted leading column")
	state = flat_state()
	state.attributes[20].fill(0x74)
	state.step(false, true, false, false)
	check(state.y, 199, "Down traverses 0x74 support")
	state = flat_state()
	state.step(false, true, false, false)
	check(state.y, 191, "Down does not traverse solid support")
	state.step(true, false, false, false)
	state.step(true, false, true, false)
	check([state.frame, state.facing], [10, 1], "Air reversal uses old facing for vertical pose")
	state.step(true, false, true, false)
	check(state.frame, 20, "Air pose catches up to facing next update")

	state = flat_state()
	state.step(false, false, false, true)
	state.step(false, false, false, false)
	check(state.frame, 2, "Right stop pose")
	state.step(false, false, false, true)
	check(state.frame, 4, "Resume advances preserved walking index")
	for i in range(18):
		state.step(false, false, false, false)
	check(state.frame, 0, "Eighteen idle updates return to standing")

	state = flat_state()
	state.x = 200
	state.y = 100
	state.camera_x = 5
	state.camera_y = 5
	var world: Vector2i = state.world_position()
	state.scroll_camera()
	check(state.world_position(), world, "Camera preserves world position")
	check([state.x, state.y, state.camera_x, state.camera_y], [192,108,6,4], "Camera takes only one step")
	state.x = 144
	state.y = 108
	state.scroll_camera()
	check([state.x, state.y, state.camera_x, state.camera_y], [144,108,6,4], "Threshold equality does not scroll")
	var backgrounds: Array = []
	for i in range(5):
		state.render_step()
		backgrounds.append(state.background_frame)
	check(backgrounds, [1,2,3,0,1], "Background animation advances once per render")
	print("WR1 motion: %d checks, %d failures" % [checks, failures])
	quit(1 if failures else 0)
